### ISSUE TITLE
could you use your own nick in the identifier

### ISSUE THREAD

**Issue by lad1337** [groenlid/xdm-anime-plugin-repo#1]
if you use de.lad1337.anime this restricts me from creating one with that name 
well they fight for the version

if you do change this updates are not applied to the already installed plugins with the "old" identifier

ps same for de.lad1337.uranime

**Comment by groenlid** [comment]
Sure thing. I'll change it now.
Didn't really bother changing it when initially creating it since the repo
is just made out of boredom and first attempt at anything in python.

The repository is more or less a copy/paste from other plugins in your
main-plugin-repo as the documentation for xdm-plugin-development is very
sparse.

M.v.h
Mats Grønlid

2013/12/11 lad1337 notifications@github.com
