### ISSUE TITLE
series data does not match http://urani.me/

### ISSUE THREAD

**Issue by seertenedos** [groenlid/xdm-anime-plugin-repo#6]
I was doing some testing and happened to choose the anime "Gundam Build Fighters" found here http://urani.me/anime/viewepisodes/1302/Gundam%20Build%20Fighters. What i found interesting is the series has 13 episodes on urani.me but only 5 episodes get listed in XDM.  I investigated the API you are using for the series http://groenlid.no-ip.org/api/animedetails/1302 and found it only returns 5 episodes. I think the source code has been left pointing to a test API url or the API is not kept up to date.

The plugin is a great idea but it needs to be able to get all the data on a series to be useful. That said that is the only issue i found so far.

**Comment by groenlid** [comment]
Don't worry @seertenedos , you'll definitely find more issues in the future :POk. So the reason why you get different data is correct as you say, because the xdm-plugin is pointing to the "wrong" api endpoint.
It's pointing to my staging sever which I use to test a new api that I'm developing which will in time replace the current one on urani.me.
I will probably not change the endpoints before the api reaches production.

But I could set up a rsync/cron/mysqldump job to transfer the newest data from urani.me to the staging server say, once a day?

Thanks for reporting bugs btw ;)

Edit: Test it now...

**Comment by seertenedos** [comment]
Thanks, That would be great.

Bugs are always expected in new code :)  I plan to learn python as well so
i may be able to help you out in future.  Currently only a C# developer. Do
you have anywhere to post suggestions or questions or do you prefer it to
be posted here?

**Comment by seertenedos** [comment]
Can confirm the series seems to have all the eps now
